Use template literals over string concatenation
asztal/react-intl-modules-loader pull request #2
Opened 2018-10-02 11:35 UTC by tomtomdotcom

2018-10-02 12:15 UTC, asztal requested changes
All for it, just some minor changes to make 👌

2018-10-02 12:15 UTC, asztal commented on index.js
> +                case "object": check(obj[key], `${path}."${key}`); break;
Looks like a rogue `"`?

2018-10-02 12:15 UTC, asztal commented on index.js
> +                const nested = convert(obj[key], `${path} + ${key}.`);
Here too, it needs to be `${path}${key}.` :)

2018-10-03 10:37 UTC, tomtomdotcom commented
^ PR updated with issues.

2018-10-03 12:44 UTC, merged